### PR TITLE
Added Kenneth as a committer

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Review by ctubbsii — APPROVED** [review]

**Comment by keith-turner** [comment]
Thanks for the quick review @ctubbsii. @kpm1985  would you be interested in trying to merge this? Not sure the instructions I sent about apache and git were the best, but we can help with any issue you bump into.

**Comment by kennethmcfarland** [comment]
I'd be happy to try and merge it, but I am a little foggy after reading the
new committers doc and stuff. For instance, should I have a password to use
with the account id?

**Comment by ctubbsii** [comment]
@kpm1985 You should have received an email with instructions for setting your password and managing your account at https://id.apache.org

**Review by kennethmcfarland — APPROVED** [review]

**Comment by kennethmcfarland** [comment]
@ctubbsii Thank you, I found it and set it up. I linked the accounts and
enabled two factor auth. Pretty smooth so far. Thank you guys for the support.

**Pull request merged**
