### PR TITLE
Rolled Gemfile.lock back to previous version from e1a6dcd

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Comment by keith-turner** [comment]
@cjmctague  I opened this RE our conversation on #60 .  Can you run the following in your env with this file?  One thing I was unsure about was if you had to run `bundle update` or if you could omit this step?  @mikewalch  when do we want to update these deps?  It seems like I remember you mentioning keeping these in sync with Github versions, but I am not sure.

```
bundle install
bundle exec jekyll serve
```

**Comment by cjmctague** [comment]
@keith-turner I pulled down this PR branch and this is what I got
```
Bundle complete! 2 Gemfile dependencies, 77 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
bundle exec jekyll serve
Configuration file: */incubator-fluo-website/_config.yml
Configuration file: */incubator-fluo-website/_config.yml
*/therubyracer-0.12.2/lib/v8/conversion.rb:21: warning: constant ::Fixnum is deprecated
jekyll 3.3.1 | Error:  wrong argument type Class (expected Module)
```
Also
```
gem -v
2.6.12
bundle -v
Bundler version 1.15.1
```

**Comment by keith-turner** [comment]
> jekyll 3.3.1 | Error:  wrong argument type Class (expected Module)

I have no idea what is causing that.  @ctubbsii, @mikewalch or @mjwall  any clues?

I tried running the following on my system :

> $ bundle update github-pages

and was unable to update to `nokogiri (1.8.0)` because my version of Ruby was too old.  Maybe I just need a newer version of Ruby.

**Comment by cjmctague** [comment]
When I installed everything on this computer I followed the instructions on the [READMD.md](https://github.com/apache/incubator-fluo-website#contributions) and these were the results I got. I had to run `bundle update` to utilize the freshly installed RubyGems because it would error out without it. That updated the Gem.lock file. It didn't seem to be backwards compatible with older versions.

I feel like it would be best to update everything as anyone that comes to contribute something to the website and follows those instructions will get the latest RubyGems version. 

If we don't want to update them, the I'd say add instructions to the README.md to install specific versions of RubyGems.

```
gem install rubygems-update -v X.X.X
```

**Comment by mjwall** [comment]
ah, good old rubyracer.  What OS are you on and version of ruby?

**Comment by mjwall** [comment]
> gem install rubygems-update -v X.X.X

I don't think that is necessary.  Simply put a version in the Gemfile to pin it to the same version for everyone.  

There has also been debate about whether Gemfile.lock belongs in version control or not. I tend for follow http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/, which says check it in unless you are building a gem

**Comment by cjmctague** [comment]
@mjwall 
```
ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```

**Comment by keith-turner** [comment]
I has a realization about why checking in gemfile.lock may be important.  We are rendering the website ourselves.  Using the same versions of dependencies to do this ensures that different people can consistently render the site.  If Github were rendering the site, then I don't think it would be as important.

**Review by mikewalch — APPROVED** [review]
+1

**Comment by mikewalch** [comment]
I am not 100% sure what is causing the problem but it could be due to the `therubyracer` gem not having an exact version in the Gemfile.  Using the rolled back Gemfile, update the version of `therubyracer` to `0.12.2`.  If that fixes the problem, we can update the Gemfile to use this version.

```
--- a/Gemfile
+++ b/Gemfile
@@ -1,3 +1,3 @@
 source 'https://rubygems.org'
 gem 'github-pages', '110', group: :jekyll_plugins
-gem 'therubyracer'
+gem 'therubyracer', '0.12.2'
```

**Comment by cjmctague** [comment]
Using the rolled back file,`therubyracer` was on 0.12.2 and I still produced the same error.

**Comment by keith-turner** [comment]
> Using the rolled back file,therubyracer was on 0.12.2 and I still produced the same error.

For me the problem was `nokogiri`.  So I tried rolling back the roll back of the changes to gemfile.loc.  Then I added a version of '0.12.3' for rubyracer and a version of `1.6.8.1` for nokogiri.  This works for me.  @cjmctague  does this latest commit with '0.12.3' work for you?

**Comment by keith-turner** [comment]
Not sure what is wrong with this PR, but new commits do not show up unless I open and close it

**Comment by keith-turner** [comment]
Also, I ran `bundle update` after setting the versions in `Gemfile`

**Comment by cjmctague** [comment]
@keith-turner This pull request works for me

**Comment by keith-turner** [comment]
I changed this significantly after @mikewalch  approved.  I'll wait for another approval before merging.

**Comment by keith-turner** [comment]
> @keith-turner This pull request works for me

@cjmctague , curious if you considered that approval to merge?  We usually `+1` in a comment or use the GH approval mechanism.

**Comment by cjmctague** [comment]
I was saying it didn't error out anymore but +1

**Pull request merged**
