### PR TITLE
Git Username

### PR DESCRIPTION
**Pull request by kennethmcfarland**
This change updates my git username.

### CODE REVIEW

**Review by ctubbsii — COMMENTED** [review]
@kennethmcfarland Your old GitHub user (@kpm1985) is still associated with your Apache ID, and not this new GitHub user.

You should first link your new GitHub user to your Apache ID at id.apache.org and/or gitbox.apache.org, once you've reestablished control over your Apache account.

Once that is done, we'll be able to verify that this change is authentic because the new GitHub user name should be reflected in your profile at https://whimsy.apache.org/roster/committee/fluo and have confidence to merge this for you.

Alternatively, if you have already regained access to your Apache account, then please feel free to go ahead and merge this change yourself (but you should still update the GitHub user linked to your Apache ID at id.apache.org and/or gitbox.apache.org).

**Comment by kennethmcfarland** [comment]
@ctubbsii Thank you for reviewing this. I have emailed an updated ICLA off to the secretary today so I should regain access to the Apache account shortly and will link everything up. Thank you for continuing to help provide help.

**Comment by kennethmcfarland** [comment]
@ctubbsii 

I have successfully regained access to my Apache account and have updated my git username at id.apache.org. I also linked the ASF on this github account.

**Review by ctubbsii — APPROVED** [review]
LGTM. Merge whenever!

**Comment by kennethmcfarland** [comment]
I'm not sure I can merge because under the "This branch has no conflicts" it says "Only those with write access to this repository can merge pull requests".  If I've made another error I apologize in advance.

**Comment by ctubbsii** [comment]
> I'm not sure I can merge because under the "This branch has no conflicts" it says "Only those with write access to this repository can merge pull requests". If I've made another error I apologize in advance.

Hmm, it seems that your GitHub account isn't fully sync'd in GitBox. Try going to https://gitbox.apache.org/setup/ and ensuring that everything is set up correctly there. If everything is set up correctly, you should see your GitHub user show up in https://github.com/orgs/apache/teams/fluo-committers/members 

I could merge for you, but I think it's probably worth using this issue as an exercise to make sure everything is set up correctly. If you can't get it to work after a few days (it may take a few days to sync), I would contact INFRA.

**Comment by kennethmcfarland** [comment]
@ctubbsii Thank you for continuing to be so helpful. I've updated the gitbox information and the LDAP listed the write access to the repositories so I think all I can do now is just wait for it to sync like you said. I also agree that I'd like to be able to merge this so that everything is working and its a good small little test to get things straightened out. Again, thank you for your help!

**Pull request merged**
