### PR TITLE
fixes #59

### LINKED ISSUE #59: Website spelling to fix
I just did a quick run through of the website and these are the problems I found. I didn't dig too extensively but this is the gist.

------------
- [Release.md Line 7](https://github.com/apache/incubator-fluo-website/blame/gh-pages/pages/release.md#L7) seperately should be separately 
------------
- [Tour: Writing Code line 17](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/writing-code.md#L17) excercises should be exercises 
- [Tour: Basic read and write line 11 ](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/basic-read-write.md#L11) excercise method should be exercise 
- [Tour: Basic  read and write line 22 - 25](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/basic-read-write.md#L22) snaphot should probably be snapshot.
- [Tour: Snapshot Isolations Code line 6](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/snapshot-isolation-code.md#L6) excercise method should be exercise 
- [Tour: Collision Code line 6](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/collision-code.md#L6) excercise method should be exercise 
- [Tour: Write Skew Code line 6 ](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/write-skew-code.md#L6) excercise method should be exercise 
- [Tour: Scanning code Line 7](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/scanning-code.md#L7) excercise method should be exercise
- [Tour: Scanning code Line 50](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/scanning-code.md#L50) lamda's should be  lambda's
- [Tour: Fetching multiple Cells line 27](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/multi-get.md#L27)excercise method should be exercise
- [Tour: Observer example line 32](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/observer_example.md#L32) excercise method should be exercise
- [Tour: Example 1 line 137, 145, 547](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/exercise-1.md#L137) All references to excercise should be exercise
- [Tour: Row locking line 61](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/row-locking.md#L61) excercise method should be exercise
- [Tour: Weak Code line 40](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/weak-code.md#L40) excercise method should be exercise
- [Tour: Applications Configuration line 124](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/application-configuration.md#L124) excercise method should be exercise
- [Tour: Memory limits and self notify code line 74](https://github.com/apache/incubator-fluo-website/blame/gh-pages/tour/mem-self-ntfy-code.md#L74) excercise method should be exercise
------------

- [Docs index page line 11](https://github.com/apache/incubator-fluo-website/blame/gh-pages/docs/index.md#L11) seperate should be separate 
- [Api.md line 11](https://github.com/apache/incubator-fluo-website/blame/gh-pages/pages/api.md#L11) seperate should be separate 
- [getinvolved.md line 11](https://github.com/apache/incubator-fluo-website/blame/gh-pages/pages/getinvolved.md#L11) disscussion should be discussion 
- [How to contribute line 31](https://github.com/apache/incubator-fluo-website/blame/gh-pages/pages/how-to-contribute.md#L31) insructions should be instructions 

------------

- [Blog Post immutable bytes.md line 19](https://github.com/apache/incubator-fluo-website/blame/gh-pages/_posts/blog/2016-11-09-immutable-bytes.md#L19) analagous should be analogous 
- [Fluo recipes 1.0.0-incubation.md release line 29](https://github.com/apache/incubator-fluo-website/blame/7755ad6012a6abdb9744674d1d9a8243652b15cc/_posts/release/2016-10-28-fluo-recipes-1.0.0-incubating.md#L29) wehn should be when
- [fluo-recipes/1.0.0-incubating/index.md line 8](https://github.com/apache/incubator-fluo-website/blame/7755ad6012a6abdb9744674d1d9a8243652b15cc/docs/fluo-recipes/1.0.0-incubating/index.md#L8) additinal should be additional 
- [fluo-recipes/1.0.0-incubating/index.md line 9](https://github.com/apache/incubator-fluo-website/blame/7755ad6012a6abdb9744674d1d9a8243652b15cc/docs/fluo-recipes/1.0.0-incubating/index.md#L9) seperately should be separately

### PR DESCRIPTION
**Pull request by cjmctague**
-Fixes various spelling throughout website
-Updated people.md page

### CODE REVIEW

**Review by keith-turner — APPROVED** [review]

**Comment by keith-turner** [comment]
I opened #61 to fix the tour code related to the website.

**Comment by keith-turner** [comment]
@cjmctague I updated the website.  The source for the website is in the gh-pages branch.  The content for the website is in the asf-site branch.  The script `_scripts/git-hooks/post-commit` will automatically update the asf-site branch.   I manually (I have not configured it as a post commit hook because I don't want it to always run) ran that script while in the gh-pages branch and it updated the asf-site branch.

I had a problem with the Gemfile.lock file while attempting this.  I don't understand this file too well, why did you update it in the PR?

**Comment by cjmctague** [comment]
@keith-turner Thanks! I figured the gh-page wasn't the actual website and I saw the asf-site branch but wasn't sure how to get it there from gh-page. I was gonna try to look it up before asking. Didn't realize there was a script. 

My computer did it automatically. I had to install everything to run the website locally on the localhost. When I installed everything I got the most up-to-date gems which in return updated that file. I tried using the old file but it didn't work for me. Only when I ran `bundle install` and `bundle update` and would it run locally. So that is what updated the `Gemfile.lock` file

**Comment by keith-turner** [comment]
> My computer did it automatically.

Would you be ok with me rolling the file back for now?  If I did would the older version still work for you?  Some of the newer dependencies in the file are not working in my env.

> When I installed everything I got the most up-to-date gems which in return updated that file.

What command did you run to do this?

**Comment by cjmctague** [comment]
> Would you be ok with me rolling the file back for now? If I did would the older version still work for you? Some of the newer dependencies in the file are not working in my env.

Sure I can just install all the old ones manually

> What command did you run to do this?

`gem update` will update all of your gems to the latest version 
Then run `bundle install` then `bundle update` inside the local repo

**Pull request merged**
