### PR TITLE
Add Alan Camillo as a contributor

### PR DESCRIPTION
**Pull request by keith-turner**
@alanblueshift how does this look?  Would you like to add anything for the other columns?

### CODE REVIEW

**Comment by blueshift-brasil** [comment]
Sounds good! 👍

**Review by kennethmcfarland — APPROVED** [review]

**Comment by keith-turner** [comment]
@kpm1985 if you are interested in how to build the web site, here is some info. The raw html for the web site is stored in the asf-site branch and has to be generated using jekyll and pushed.  @ctubbsii wrote a script to automate the generation.  Below are the commands I just ran to update the website.

```bash
 # ensure local asf-site branch is up to date
 git checkout asf-site 
 git pull upstream asf-site

 # switch to gh-pages branch, update it, and build new site 
 git checkout gh-pages
 git pull upstream gh-pages 
 ./_scripts/git-hooks/post-commit 

 # switch to asf-site, look at the commit created by post-commit script, and push it if ok
 git checkout asf-site 
 git log -p
 git push upstream asf-site 
```

For me upstream is :

```java
$ git remote -v | grep upstream
upstream	https://gitbox.apache.org/repos/asf/fluo-website/ (fetch)
upstream	https://gitbox.apache.org/repos/asf/fluo-website/ (push)
```

**Comment by keith-turner** [comment]
Maybe that info should be added to the readme under a committers section?

**Comment by kennethmcfarland** [comment]
That sounds like a good idea. Thank you for sharing the info, so the next time I can update the website and not leave a job half done :+1:

**Comment by kennethmcfarland** [comment]
Hi Keith,

Following up on this, I just gave this a shot for this pull request about
the 1.2 documentation by Mike Walch:

https://github.com/apache/fluo-website/pull/115

I needed to install some ruby stuff and on Ubuntu the only hitch I had was
to sudo apt-get install ruby-dev so it had the header files. The rest was
follow the prompts and your instructions and it works great.

**Pull request merged**
